// Auto-generated by OpenLane
module systolic_top_uart_4parallel_q8_24(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input opcode_in0,
  input opcode_in1,
  input opcode_in2,
  input opcode_in3,
  input start_in,
  input tx_in,
  input clk_in,
  input rst_in,
  output done_out,
  output busy_out,
  output rx_out,
  output out4,
  output out5,
  output out6,
  output out7,
  output out8
);
endmodule
