/* Generated by Yosys 0.43 (git sha1 ead4718e5, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module systolic_top_uart_4parallel_q8_24(opcode_in0, opcode_in1, opcode_in2, opcode_in3, start_in, tx_in, clk_in, rst_in, done_out, busy_out, rx_out, out4, out5, out6, out7, out8);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  output busy_out;
  wire busy_out;
  input clk_in;
  wire clk_in;
  output done_out;
  wire done_out;
  wire \fsm_state[0] ;
  wire internal_busy;
  input opcode_in0;
  wire opcode_in0;
  input opcode_in1;
  wire opcode_in1;
  input opcode_in2;
  wire opcode_in2;
  input opcode_in3;
  wire opcode_in3;
  output out4;
  wire out4;
  output out5;
  wire out5;
  output out6;
  wire out6;
  output out7;
  wire out7;
  output out8;
  wire out8;
  input rst_in;
  wire rst_in;
  output rx_out;
  wire rx_out;
  input start_in;
  wire start_in;
  input tx_in;
  wire tx_in;
  sky130_fd_sc_hd__inv_2 _05_ (
    .A(rst_in),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a21o_2 _06_ (
    .A1(\fsm_state[0] ),
    .A2(start_in),
    .B1(internal_busy),
    .X(_04_)
  );
  sky130_fd_sc_hd__and2b_2 _07_ (
    .A_N(start_in),
    .B(\fsm_state[0] ),
    .X(_00_)
  );
  sky130_fd_sc_hd__inv_2 _08_ (
    .A(rst_in),
    .Y(_02_)
  );
  sky130_fd_sc_hd__inv_2 _09_ (
    .A(rst_in),
    .Y(_03_)
  );
  sky130_fd_sc_hd__dfstp_2 _10_ (
    .CLK(clk_in),
    .D(_00_),
    .Q(\fsm_state[0] ),
    .SET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_2 _11_ (
    .CLK(clk_in),
    .D(internal_busy),
    .Q(busy_out),
    .RESET_B(_02_)
  );
  sky130_fd_sc_hd__dfrtp_2 _12_ (
    .CLK(clk_in),
    .D(_04_),
    .Q(internal_busy),
    .RESET_B(_03_)
  );
  sky130_fd_sc_hd__buf_2 _13_ (
    .A(1'b0),
    .X(done_out)
  );
  sky130_fd_sc_hd__buf_2 _14_ (
    .A(1'b0),
    .X(out4)
  );
  sky130_fd_sc_hd__buf_2 _15_ (
    .A(1'b0),
    .X(out5)
  );
  sky130_fd_sc_hd__buf_2 _16_ (
    .A(1'b0),
    .X(out6)
  );
  sky130_fd_sc_hd__buf_2 _17_ (
    .A(1'b0),
    .X(out7)
  );
  sky130_fd_sc_hd__buf_2 _18_ (
    .A(1'b0),
    .X(out8)
  );
  sky130_fd_sc_hd__buf_2 _19_ (
    .A(1'b0),
    .X(rx_out)
  );
endmodule
